// AUTO-GENERATED — edit versions.yaml or generator code, then run `sbt generate`

package io.github.nafg.scalacoptions.options

trait V2_11_7_+ extends V2_11_6_+ {
  /**
   * Configure XML parsing: `_' for all, `-Xxml:help' to list
   */
  def Xxml(`_,property,-property`: String) = List("-Xxml:" + `_,property,-property`)

  /**
   * Set the heuristics for inlining decisions. (at-inline-annotated,everything) default:at-inline-annotated
   */
  def YoptInlineHeuristics(strategy: String) = List("-Yopt-inline-heuristics:" + strategy)

  /**
   * Enable optimizer warnings: `_' for all, `-Yopt-warnings:help' to list
   */
  def YoptWarnings(`_,warning,-warning`: String) = List("-Yopt-warnings:" + `_,warning,-warning`)

  /**
   * Do not add the ScalaInlineInfo attribute to classfiles generated by -Ybackend:GenASM
   */
  def YskipInlineInfoAttribute = List("-Yskip-inline-info-attribute")

  /**
   * Warn when local and private vals, vars, defs, and types are unused.
   */
  override def YwarnUnused = List("-Ywarn-unused")
}
