// AUTO-GENERATED — edit versions.yaml or generator code, then run `sbt generate`

package io.github.nafg.scalacoptions.options

trait V2_12 extends V2 {
  /**
   * destination for generated classfiles.
   */
  override def d(`directory|jar`: String) = List("-d", `directory|jar`)

  /**
   * Enable or disable language features: `_' for all, `-language:help' to list choices.
   */
  override def language(features: String) = List("-language:" + features)

  /**
   * Enable optimizations: `_' for all, `-opt:help' to list choices.
   */
  def opt(`_,optimization,-optimization`: String) = List("-opt:" + `_,optimization,-optimization`)

  /**
   * Enable optimizer warnings: `_' for all, `-opt-warnings:help' to list choices.
   */
  def optWarnings(`_,warning,-warning`: String) = List("-opt-warnings:" + `_,warning,-warning`)

  def target(target: String) = List("-target:" + target)

  /**
   * <n>                Calls to @elidable methods are omitted if method priority is lower than argument
   */
  override def XelideBelow = List("-Xelide-below")

  def Xexperimental = List("-Xexperimental")

  def XfatalWarnings = List("-Xfatal-warnings")

  def XfullLubs = List("-Xfull-lubs")

  def Xfuture = List("-Xfuture")

  /**
   * <file>    Generate the phase graphs (outputs .dot files) to fileX.dot.
   */
  def XgeneratePhaseGraph = List("-Xgenerate-phase-graph")

  /**
   * Enable or disable specific warnings: `_' for all, `-Xlint:help' to list choices.
   */
  def Xlint(`_,warning,-warning`: String) = List("-Xlint:" + `_,warning,-warning`)

  def XlogFreeTerms = List("-Xlog-free-terms")

  def XlogFreeTypes = List("-Xlog-free-types")

  def XlogImplicitConversions = List("-Xlog-implicit-conversions")

  def XlogImplicits = List("-Xlog-implicits")

  def XlogReflectiveCalls = List("-Xlog-reflective-calls")

  /**
   * <path>              Class for manifest's Main-Class entry (only useful with -d <jar>)
   */
  def XmainClass = List("-Xmain-class")

  /**
   * <n>         Maximum filename length for generated classes
   */
  def XmaxClassfileName = List("-Xmax-classfile-name")

  def XmixinForceForwarders(mode: String) = List("-Xmixin-force-forwarders:" + mode)

  def XnoUescape = List("-Xno-uescape")

  /**
   * Print out program after <phases>
   */
  def Xprint(phases: String) = List("-Xprint:" + phases)

  def XprintPos = List("-Xprint-pos")

  def XprintTypes = List("-Xprint-types")

  def Xreporter(classname: String) = List("-Xreporter", classname)

  /**
   * <class>             Show internal representation of class.
   */
  def XshowClass = List("-Xshow-class")

  /**
   * <object>           Show internal representation of object.
   */
  def XshowObject = List("-Xshow-object")

  def XshowPhases = List("-Xshow-phases")

  /**
   * <classname>      Specify a custom method for reading source files.
   */
  override def XsourceReader = List("-Xsource-reader")

  def XstrictInference = List("-Xstrict-inference")

  /**
   * Configure XML parsing.: `_' for all, `-Xxml:help' to list choices.
   */
  def Xxml(`_,property,-property`: String) = List("-Xxml:" + `_,property,-property`)

  /**
   * Browse the abstract syntax tree after <phases>
   */
  def Ybrowse(phases: String) = List("-Ybrowse:" + phases)

  def Ydebug = List("-Ydebug")

  def YdocDebug = List("-Ydoc-debug")

  /**
   * <dir>                     Dump the generated bytecode to .class files (useful for reflective compilation that utilizes in-memory classloaders).
   */
  override def YdumpClasses = List("-Ydump-classes")

  /**
   * <dir>                         Generate a parallel output directory of .asmp files (ie ASM Textifier output).
   */
  override def YgenAsmp = List("-Ygen-asmp")

  def YideDebug = List("-Yide-debug")

  def YinferArgumentTypes = List("-Yinfer-argument-types")

  def YissueDebug = List("-Yissue-debug")

  /**
   * Log operations during <phases>
   */
  def Ylog(phases: String) = List("-Ylog:" + phases)

  def YlogClasspath = List("-Ylog-classpath")

  def YmacroDebugLite = List("-Ymacro-debug-lite")

  def YmacroDebugVerbose = List("-Ymacro-debug-verbose")

  @deprecated("See doc comment", "") def YmacroNoExpand = List("-Ymacro-no-expand")

  def YnoAdaptedArgs = List("-Yno-adapted-args")

  def YoptInlineHeuristics(strategy: String) = List("-Yopt-inline-heuristics:" + strategy)

  /**
   * <package/Class.method>  Print a summary of inliner activity; `_` to print all, prefix match to select.
   */
  def YoptLogInline = List("-Yopt-log-inline")

  /**
   * <package/Class.method>       Trace the optimizer progress for methods; `_` to print all, prefix match to select.
   */
  def YoptTrace = List("-Yopt-trace")

  def YoverrideObjects = List("-Yoverride-objects")

  def YoverrideVars = List("-Yoverride-vars")

  def YpartialUnification = List("-Ypartial-unification")

  def YpatmatDebug = List("-Ypatmat-debug")

  /**
   * <n>               off
   */
  def YpatmatExhaustDepth = List("-Ypatmat-exhaust-depth")

  def YposDebug = List("-Ypos-debug")

  def YpresentationAnyThread = List("-Ypresentation-any-thread")

  /**
   * <n>                 Wait number of ms after typing before starting typechecking
   */
  override def YpresentationDelay = List("-Ypresentation-delay")

  /**
   * <file>                Log presentation compiler events into file
   */
  override def YpresentationLog = List("-Ypresentation-log")

  /**
   * <file>             Replay presentation compiler events from file
   */
  override def YpresentationReplay = List("-Ypresentation-replay")

  def YquasiquoteDebug = List("-Yquasiquote-debug")

  def YreifyDebug = List("-Yreify-debug")

  /**
   * <path>                     Write repl-generated classfiles to given output directory (use "" to generate a temporary dir)
   */
  override def YreplOutdir = List("-Yrepl-outdir")

  def YreplSync = List("-Yrepl-sync")

  /**
   * (Requires -Xshow-class or -Xshow-object) Show after <phases>
   */
  def Yshow(phases: String) = List("-Yshow:" + phases)

  def YshowMemberPos = List("-Yshow-member-pos")

  def YshowSymkinds = List("-Yshow-symkinds")

  def YshowSymowners = List("-Yshow-symowners")

  def YshowSyms = List("-Yshow-syms")

  def YshowTrees = List("-Yshow-trees")

  def YshowTreesCompact = List("-Yshow-trees-compact")

  def YshowTreesStringified = List("-Yshow-trees-stringified")

  def YtyperDebug = List("-Ytyper-debug")

  def YwarnAdaptedArgs = List("-Ywarn-adapted-args")

  def YwarnDeadCode = List("-Ywarn-dead-code")

  def YwarnInaccessible = List("-Ywarn-inaccessible")

  def YwarnInferAny = List("-Ywarn-infer-any")

  def YwarnNullaryOverride = List("-Ywarn-nullary-override")

  def YwarnNullaryUnit = List("-Ywarn-nullary-unit")

  def YwarnNumericWiden = List("-Ywarn-numeric-widen")

  def YwarnUnusedImport = List("-Ywarn-unused-import")

  def YwarnValueDiscard = List("-Ywarn-value-discard")
}
