// AUTO-GENERATED — edit versions.yaml or generator code, then run `sbt generate`

package io.github.nafg.scalacoptions.options

trait V3_1 extends V3 {
  /**
   * Enable one or more language features.
   */
  override def language(features: String) = List("-language:" + features)

  /**
   * Show source code line numbers.
   */
  override def printLines = List("-print-lines")

  /**
   *  Generate static forwarders even for non-top-level objects (Scala.js only)
   */
  override def scalajsGenStaticForwardersForNonTopLevelObjects = List("-scalajs-genStaticForwardersForNonTopLevelObjects")

  /**
   * rebases source URIs from uri1 to uri2 (or to a relative URI) for source maps (Scala.js only)
   */
  override def scalajsMapSourceURI = List("-scalajs-mapSourceURI")

  /**
   * Utilize the java.class.path in classpath resolution.
   */
  def usejavacp = List("-usejavacp")

  /**
   * Print a synopsis of verbose options.
   */
  def V = List("-V")

  /**
   * Print a synopsis of warning options.
   */
  def W = List("-W")

  /**
   * Configure compiler warnings.
   */
  def Wconf = List("-Wconf")

  /**
   * Fail the compilation if there are any warnings.
   */
  def Werror = List("-Werror")

  def Wunused = List("-Wunused")

  /**
   * Class for manifest's Main-Class entry (only useful with -d <jar>)
   */
  def XmainClass = List("-Xmain-class")

  /**
   * Cook the documentation (type check `@usecase`, etc.)
   */
  def YcookDocs = List("-Ycook-docs")

  /**
   * Drop documentation when scanning source files.
   */
  def YdropDocs = List("-Ydrop-docs")

  /**
   * Dump the generated bytecode to .class files (useful for reflective compilation that utilizes in-memory classloaders).
   */
  override def YdumpClasses = List("-Ydump-classes")

  /**
   * Make non-transparent inline methods inline when typing. Emulates the old inlining behavior of 3.0.0-M3.
   */
  def YforceInlineWhileTyping = List("-Yforce-inline-while-typing")

  /**
   * List of `tasty` files in jar files that will not be loaded when using -from-tasty
   */
  override def YfromTastyIgnoreList = List("-Yfrom-tasty-ignore-list")

  /**
   * (disabled: use -language:experimental.fewerBraces instead)
   */
  def YindentColons = List("-Yindent-colons")

  /**
   * Show raw StackOverflow stacktraces, instead of decoding them into triggering operations.
   */
  override def YnoDecodeStacktraces = List("-Yno-decode-stacktraces")

  /**
   * Disable experimental language features
   */
  def YnoExperimental = List("-Yno-experimental")

  /**
   * Suppress generation of generic signatures for Java.
   */
  override def YnoGenericSignatures = List("-Yno-generic-signatures")

  /**
   * Disable kind polymorphism.
   */
  override def YnoKindPolymorphism = List("-Yno-kind-polymorphism")

  /**
   * Read documentation from tasty.
   */
  def YreadDocs = List("-Yread-docs")

  /**
   * Warn if an operator is defined without a @targetName annotation
   */
  override def YrequireTargetName = List("-Yrequire-targetName")

  /**
   * Ensure safe initialization of objects
   */
  override def YsafeInit = List("-Ysafe-init")
}
