defaults: {}
pull_request_rules:
  - name: Automatically merge successful scala-steward PRs
    conditions:
      - author=scala-steward
      - check-success=Build and Test (ubuntu-latest, 2.12.15, temurin@11)
      - check-success=Build and Test (ubuntu-latest, 2.13.6, temurin@11)
    actions:
        merge:
            strict: true
