defaults: {}
queue_rules:
  - name: default
    merge_conditions: []
pull_request_rules:
  - name: Automatically merge successful Scala Steward PRs
    conditions:
      - or:
          - author=scala-steward
          - author=nafg-scala-steward[bot]
      - check-success=Build and Test (ubuntu-latest, 2.12.x, zulu@8)
      - check-success=Build and Test (ubuntu-latest, 2.13.x, zulu@8)
      - check-success=Build and Test (ubuntu-latest, 3.3.x, zulu@8)
    actions:
        queue:
            name: default
