version = "3.11.0"
maxColumn = 120
preset = IntelliJ

runner {
  dialect = scala212source3
}

align {
  preset = most
  openParenDefnSite = true
}

danglingParentheses {
  defnSite = false
}

verticalMultiline {
  atDefnSite = true
}

spaces {
  beforeContextBoundColon = Always
}

newlines {
  source = keep
  topLevelStatementBlankLines = [
    {
      regex = "^Import",
      minBreaks = 0,
      blanks = {after = 2, before = 1}
    }
  ]
}

fileOverride {
  "glob:**/FastParseParser.scala" {
    spaces.beforeContextBoundColon = Never
  }
}
